#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker
- name: Download Docker GPG Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    owner: root
    group: root
    mode: "0644"

- name: Add Docker Repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    architectures: amd64
    signed_by: /etc/apt/trusted.gpg.d/docker.asc
    install_python_debian: true
    state: present

- name: Install Docker CE & Plugins
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

  