---
# tasks file for roles/gitlab
- name: Load secret vault variables
  ansible.builtin.include_vars:
    file: vault.yml
  tags: [always]

- name: Download GitLab CE repository setup script
  ansible.builtin.get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/gitlab-ce-setup.sh
    mode: "0700"
  tags: [install, repository]

- name: Run GitLab CE repository setup script
  ansible.builtin.command:
    cmd: /tmp/gitlab-ce-setup.sh
    creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
  become: true
  tags: [install, repository]

- name: Install GitLab CE
  ansible.builtin.apt:
    name: gitlab-ce
    state: present
  tags: [install, gitlab]

- name: Deploy GitLab configuration file
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: "0600"
  register: gitlab_config
  become: true
  tags: [gitlab, config]

- name: Reconfigure GitLab
  ansible.builtin.command:
    cmd: gitlab-ctl reconfigure
  become: true
  when: gitlab_config.changed 
  tags: [gitlab, config]