---
# tasks file for roles/gitlab
- name: Check if admin user exists
  ansible.builtin.command: gitlab-psql -A -t -c "SELECT EXISTS(  SELECT 1 FROM users WHERE username = '{{ vault_gitlab_admin_username }}' )"
  become: true
  register: admin_user_check
  changed_when: false

- name: Create dedicated admin user via Rails console
  ansible.builtin.command:
    cmd: >
      gitlab-rails runner "
        res = Users::CreateService.new(nil,
          username: '{{ vault_gitlab_admin_username }}',
          email: 'mustaphaboutoubdev@gmail.com',
          name: 'DevOps Admin',
          password: '{{ vault_gitlab_admin_password }}',
          password_confirmation: '{{ vault_gitlab_admin_password }}',
          organization_id: Organizations::Organization.first.id,
          skip_confirmation: true,
          admin: true
        ).execute

        raise Array(res.message).join(', ') if res.error?

        res.payload[:user].update!(admin: true)
      "
  become: true
  when: "admin_user_check.stdout == 'f'"